spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${DB_URL}

app:
  url: ${APP_URL:http://localhost:5173}